# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9227615846b6a724cf2e0f273e68c1340191b0810f3dad4d1e280947f3621aeafa31355ce0e0609b99ca32c8aa0fe7d577ae5f15f8932a60ca78ba6dcf05cd73

test:
  secret_key_base: 2142337c863c00333826e90f395b4233c4b9a4ac44527c86074582be129c73cff443a84a643e08d73e37e21b6e8d5a4911ed595c32f2cc670cd4b50f939174e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
